### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by tps800** [kost/tty2web#3]
### What version of tty2web are you using (`gotty --version`)?
v2.2.0 -- latest stable from github with go1.13.4 linux/arm
same with latest ubuntu 19.10 on amd64 with go1.13.4

### What operating system and browser are you using?
Linux Raspian 9.11

### What did you do?
go get github.com/kost/tty2web

### What did you expect to see?
Compiled version of tty2web

### What did you see instead?
`github.com/kost/tty2web/utils`
`/root/my/src/github.com/kost/tty2web/utils/flags.go:39:19: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag`
`in append:`
`        cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)`
`/root/my/src/github.com/kost/tty2web/utils/flags.go:43:6: unknown field 'EnvVar' in struct literal of type cli.StringFlag`
`/root/my/src/github.com/kost/tty2web/utils/flags.go:46:19: cannot use cli.BoolFlag literal (type cli.BoolFlag) as type cli.Flag in append:`
`        cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)`
`/root/my/src/github.com/kost/tty2web/utils/flags.go:49:6: unknown field 'EnvVar' in struct literal of type cli.BoolFlag`
`/root/my/src/github.com/kost/tty2web/utils/flags.go:52:19: cannot use cli.IntFlag literal (type cli.IntFlag) as type cli.Flag in append:`
`        cli.IntFlag does not implement cli.Flag (Apply method has pointer receiver)`
`/root/my/src/github.com/kost/tty2web/utils/flags.go:56:6: unknown field 'EnvVar' in struct literal of type cli.IntFlag`

**Comment by kost** [comment]
Thanks on reporting!

github.com/codegangsta/cli changed its API, so tty2web works with older version of codegangsta/cli. Until I update it, I would advise to build following way:

Make sure that you have $GOPATH set to valid value:
```
git clone https://github.com/kost/tty2web $GOPATH/src/tty2web
cd $GOPATH/src/tty2web
make tools
make tty2web
```

Updated README.md to reflect that (in a1a11efbddaa1885b4ff4ba1f812df5276478f03)

**Comment by kost** [comment]
Finished migration from codegangsta/cli to urfave/cli, so `go get` should work now:

Commits from 5b9c5abe024cf86719c1b59d9173f4c1810f8f76 to 5b9c5abe024cf86719c1b59d9173f4c1810f8f76

This should be working now:
```
go get github.com/kost/tty2web
```
