### ISSUE TITLE
[Feature Proposal] Improve help flag

### ISSUE THREAD

**Issue by pomdtr** [kost/tty2web#46]
tty2web should probably support an `--help` flag. Currently you are force to run `tty2web` naked to get a usage string.

Also in case of error, the error message should be printed to `stderr` by convention.

I can recommend https://clig.dev/ for more guidelines on cli application design.

**Comment by kost** [comment]
Fixed in 1071be9644faa1402f4cba52a9cfadc3ff092b88

Released in:
https://github.com/kost/tty2web/releases/tag/v2.8.0
