### ISSUE TITLE
Question: Can process run without someone viewing page?

### ISSUE THREAD

**Issue by MrCoala** [kost/tty2web#5]
I am using the latest version of tty2web and i want to use it to expose game server processes for easier maintenance. Is there a way to start a process inside a screen session with tty2web so that the process itself starts with tty2web even without someone viewing the page and that  tty2web exits when the process exits?

**Comment by kost** [comment]
Just noticed this question. Sorry about that.

Anyway, you can achieve that with screen as described in README.

In one screen run:
```
